### ISSUE TITLE
The Best Theme - Difficult to see the "current area" in VSCode's Minimap

### ISSUE THREAD

**Issue by jgodfrey** [jankohlbach/the-best-theme#1]
First - I'm a big fan of this theme!

One small issue I see is that it's nearly impossible to see the current section in VSCode's "minimap" area, as shown below:

![image](https://user-images.githubusercontent.com/1459347/108920469-4f70d300-75fa-11eb-939f-bae74545512b.png)

While the is an ever-so-slight dimming in that area, it's not really possible to find it at a glance. As a comparison, here's that same area in the default dark theme:

![image](https://user-images.githubusercontent.com/1459347/108920567-7c24ea80-75fa-11eb-90cd-4e84e2cd85ab.png)

**Comment by jankohlbach** [comment]
Hey there,
first of all, thank you so much :)
Theme installs are currently growing unexpectedly faster than I could imagine and I have no idea why, haha ...

I know there are some things that can be optimized, especially with the contrast in some places. I will have a look at this on the weekend 👍🏼

**Comment by duongdev** [comment]
Same idea for me. As a react developer, I found this theme is perfectly suited for me. Except for the minimap contrast. Hope you can improve it soon.
Thank you @jankohlbach!

**Comment by jgodfrey** [comment]
@duongdev - Yep, that's the same blog post where I discovered this great theme.

**Comment by jankohlbach** [comment]
let me know if after the next update it's enough contrast for you guys or if I better push it more

**Comment by jgodfrey** [comment]
Hi Jan,

I think the latest change is a big step in the right direction. When hovering over the "minimap" panel, but not over the "current" section, I think the contrast looks good now. However, I do find it strange that when I move my  mouse of the "current" (highlighted) section of the minimap, the area gets less contrasty (dimmer) and is harder to see. 

Looking at a number of other themes, when hovering over the highlighted section of the minimap, it becomes *more* contrasty and easier to see - which is the opposite of your theme right now for that state.

**Comment by jankohlbach** [comment]
gotcha

**Comment by jgodfrey** [comment]
Hi Jan,

I just installed the latest update (v2.0.5) and it looks really good to me now. Thanks for the prompt attention!
