### ISSUE TITLE
Different color for debug exception widget?

### ISSUE THREAD

**Issue by chickendrop89** [jankohlbach/the-best-theme#11]
Love this theme, but i wish the debug exception widget wasn't white text on pink background 

https://github.com/jankohlbach/the-best-theme/blob/628a3407b5aa54c72925a68977d3a0201dc1dca3/themes/The-Best-Theme-color-theme.json#L309

it's really hard to read

**Comment by jankohlbach** [comment]
@chickendrop89 thanks for finding, gonna fix this
could you tell me how to trigger that widget so I can see, change and test it please?

**Comment by chickendrop89** [comment]
The screenshot:
![image](https://github.com/user-attachments/assets/286ac33d-42e7-4c8d-9e6d-be960d3b52f2)

To reproduce this:
- You need to start "Run and Debug session" in vscode (the "bug" icon on the left panel), and trigger some exception/error in the debugged file (like shown in  the screenshot)
