### ISSUE TITLE
Difficult to see highlighted item in sidebar

### ISSUE THREAD

**Issue by emilime** [jankohlbach/the-best-theme#2]
Hello,

I love this theme, there is only one detail to fix imho. 
When you are moving in the sidebar using the arrow keys the highlighted line is not very visible:

![image](https://user-images.githubusercontent.com/47943/114030538-d3b1a980-987a-11eb-87dc-19201d8864ae.png)

Could you fix it? Thanks.

**Comment by jankohlbach** [comment]
Hey :)
first thanks a lot ❤
and yeah, you're absolutely right, I will have a look at it on the weekend, so I will try to fix it until the end of the week

**Comment by jankohlbach** [comment]
@emilime I published an update which should increase the contrast quite a lot, thanks for your proposal 👍🏼 
Could you let me know where you found out about the theme? I saw another raise in downloads the past days and I'm always curious if someone mentioned me 😄

**Comment by emilime** [comment]
I just tested it and I think it works fine, thank you very much!
I read about your theme in this post: https://dev.to/ratuloss/my-productivity-setup-vs-code-4o9d. :-)
