### ISSUE TITLE
Unused Variables not obvious

### ISSUE THREAD

**Issue by alyr1481** [jankohlbach/the-best-theme#3]
Hi - **big fan of this theme**, just a quick idea/enhancement idea:

In other themes when viewing a list of variables, its easy to see which ones are unused as the weight/colour of the font can change (One Dark Pro example below):
![Screenshot 2021-04-14 at 20 45 07](https://user-images.githubusercontent.com/25343343/114769598-51d1ec80-9d62-11eb-97c0-b6fa36cd48e3.png)
However in this theme that doesn't happen:
![Screenshot 2021-04-14 at 20 46 05](https://user-images.githubusercontent.com/25343343/114769717-79c15000-9d62-11eb-9c45-272354a1d5fb.png)
Am i being thick and there's a config setting I'm missing somewhere? 🙄

**Comment by jankohlbach** [comment]
Hi Alex,
thanks for being a fan ❤️ 
maybe I'm just missing out on this setting, I'll have a look at how I can add this little thing. Thanks for helping to make it even better :)

**Comment by jankohlbach** [comment]
f47593510f382e72120b66e9fc2a5997dbbe3ca3

**Comment by jankohlbach** [comment]
Hey Alex,
thanks again for your help, I just published an update that fixes this issue. I just configured this value wrong, now we have unused vars with an opacity, woop woop 🥳

**Comment by JoelPatrizio** [comment]
> Hey Alex,
> thanks again for your help, I just published an update that fixes this issue. I just configured this value wrong, now we have unused vars with an opacity, woop woop 🥳

Thanks a lot Jan, now I can confidently say this is The Best Theme 😁
