### ISSUE TITLE
Low contrast ratio in the status bar when debugging 

### ISSUE THREAD

**Issue by hkh12** [jankohlbach/the-best-theme#4]
The text and icons in the status bar are hardly visible when debugging something:
![image](https://user-images.githubusercontent.com/24871883/124705881-9c02de00-df0b-11eb-94f5-eb4295201da4.png)

And the contrast ratio is low too: https://contrast-ratio.com/#%23cc6633-on-%23cccccc

**Comment by jankohlbach** [comment]
hey @hkh12 
thanks for your feedback, I think I actually left the debugging colors on the default values and I honestly don't use them so much myself 😅 
but I will look into it on the weekend and see if I can improve that somehow 👌🏼 
hope you like the rest of the theme 😃

**Comment by jankohlbach** [comment]
@hkh12 just published a new version, should be available in a few minutes
let me know if that's better :)

**Comment by hkh12** [comment]
Yes it is, thanks!
