### ISSUE TITLE
Vscode magenta blocks with rust analyzer

### ISSUE THREAD

**Issue by Gers2017** [jankohlbach/the-best-theme#6]
Hi 👋🏽 I'm submitting this issue because while I was working with rust in vscode (rust-analyzer) 
I found some magenta blocks (see the following image) instead of the type hints, all of of this while using The Best Theme.
I'm unsure if this issue belongs here. Please let me know if it has nothing to do with the theme

### The best theme
![The best theme](https://user-images.githubusercontent.com/49139988/169356355-d32597cb-72e3-4b74-a718-61796efc4fe4.png)

### Horizon theme
![Horizon theme](https://user-images.githubusercontent.com/49139988/169356947-f57a37a0-b639-4943-8d64-8d1219128642.png)

**Comment by jankohlbach** [comment]
Hey @Gers2017 
first of all, thanks for using the theme, I hope you generally like it :)
the issue definitely belongs here, some definitions I just couldn't find where or how they are applied so I used that color 😅 
and I don't use rust ...
so thanks so much for submitting, I will take a look asap, hope I can fix this latest this week

**Comment by Gers2017** [comment]
😄 No problem, glad I could help.
And Thank you for making such a good theme I really like it

**Comment by jankohlbach** [comment]
@Gers2017 I have a little trouble reproducing the issue, I need the rust analyzer and rust correct? I have both installed but don't know how to show the types or hints?

**Comment by jankohlbach** [comment]
@Gers2017  update is out, should be fixed
let me know if it's fine or if there's anything additional :)

**Comment by Gers2017** [comment]
😅 Sorry to bother you again. Same thing happens with the vscode linked editing feature
![image](https://user-images.githubusercontent.com/49139988/170835663-c3b35dbd-aa69-4260-bdd2-c41bf3cb39b9.png)
![image](https://user-images.githubusercontent.com/49139988/170835724-e65f6c50-73e4-4a96-9064-de92d5aabaca.png)
What's weird about this is that it only shows up with the vscode built-in feature but not with the [auto rename tag extension](https://github.com/formulahendry/vscode-auto-rename-tag).
![image](https://user-images.githubusercontent.com/49139988/170836381-aaad266b-6bcc-47cf-b8f4-fa173eba6633.png)
