### ISSUE TITLE
magenta in linked editing feature

### ISSUE THREAD

**Issue by jankohlbach** [jankohlbach/the-best-theme#7]
😅 Sorry to bother you again. Same thing happens with the vscode linked editing feature
![image](https://user-images.githubusercontent.com/49139988/170835663-c3b35dbd-aa69-4260-bdd2-c41bf3cb39b9.png)
![image](https://user-images.githubusercontent.com/49139988/170835724-e65f6c50-73e4-4a96-9064-de92d5aabaca.png)
What's weird about this is that it only shows up with the vscode built-in feature but not with the [auto rename tag extension](https://github.com/formulahendry/vscode-auto-rename-tag).
![image](https://user-images.githubusercontent.com/49139988/170836381-aaad266b-6bcc-47cf-b8f4-fa173eba6633.png)

_Originally posted by @Gers2017 in https://github.com/jankohlbach/the-best-theme/issues/6#issuecomment-1140302194_

**Comment by jankohlbach** [comment]
@Gers2017 update should be out in a few minutes, then it's fixed
thanks again for the feedback

**Comment by Gers2017** [comment]
Neat! thank you for this change. The theme looks better, I'm going to recommend it 😃
